### ISSUE TITLE
Add a static IP address

### ISSUE THREAD

**Issue by miyo** [fpga-design-contest/ad-refkit#3]
In order to access ZYBO Z7-20 without setting IP address manually, it is better to add a static IP address for eth0 as default in creating root file system.

**Comment by miyo** [comment]
1. create /etc/netplan/01-netcfg.yaml

```
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      dhcp6: no
      addresses:
        - 192.168.2.200/24
      gateway4: 192.168.2.1
      nameservers:
        addresses: [192.168.2.1]
        search: [local]
```

2. run `netplan generate`

The command generates the followings.
 
- /run/systemd/network/10-netplan-ens3.network
- /run/systemd/resolve/resolv.conf

3. disable `networking` and enable `systemd-networkd`

```
$ systemctl disable networking
$ systemctl enable systemd-networkd.service
```
